# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aeaf70cd6bad955559c4a8b43ccea817"
name = "insta-app"
handle = "insta-app-6"
application_url = "https://subjects-ticket-eggs-allergy.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-e65c4dd2.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://subjects-ticket-eggs-allergy.trycloudflare.com/auth/callback",
  "https://subjects-ticket-eggs-allergy.trycloudflare.com/auth/shopify/callback",
  "https://subjects-ticket-eggs-allergy.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
